# golangci-lint configuration for Yakusoku
# Run with: golangci-lint run

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic
    - revive
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Println
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic
          - revive
      - path: examples/
        linters:
          - errcheck
          - revive
      - path: sdk/go/examples/
        linters:
          - errcheck
          - revive

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jt-chihara/yakusoku
