# golangci-lint configuration for Yakusoku
# Run with: golangci-lint run

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - revive

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/jt-chihara/yakusoku
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Printf
      - fmt.Println
      - (io.Closer).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - revive
    - path: examples/
      linters:
        - errcheck
        - revive
    - path: sdk/go/examples/
      linters:
        - errcheck
        - revive
